### ISSUE TITLE
port is not defined

### ISSUE THREAD

**Issue by lejacobroy** [MagicCube/rpi-man#1]
I followed the instructions, and have Node.js 6.10.2 installes on my Pi3B.
Everything installed flawlessly, but when I start the server, I get this error 
````
/opt/rpi-man/lib/server.js:28
        : "Port " + port;
                    ^

ReferenceError: port is not defined
    at Server.server.onError (/opt/rpi-man/lib/server.js:28:21)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
````

**Comment by michalroxorpl** [comment]
I have the same problem as @lejacobroy, please @MagicCube, could you take closer look at that error? It seems that no one will be able to solve it as fast as you could as a developer :-)

**Comment by snoof** [comment]
i have the same error
